### ISSUE TITLE
Add Support to Donut for Document AI 

### ISSUE THREAD

**Issue by KaifAhmad1** [groq/groq-python#86]
Add support to Clova AI Donut for real-time document analysis, enhancing Document AI capabilities on Groq Cloud https://huggingface.co/naver-clova-ix/donut-base

**Comment by hozen-groq** [comment]
@KaifAhmad1 Hi there! 👋 Thanks for the feature request. If you haven't already, please join our developer community on [Discord](https://discord.gg/invite/groq) to submit feature requests in the #feature-requests channel so that others can also upvote ones they'd like to see us support! We triage that channel and pass on popular requests to our Product and Engineering teams.
